# Site settings
title: ePosition for IoT
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: ePosition is a new Universal Resource Identifier that every "thing" in IoT owns an email address type of identification. Instead of @, it uses #.

baseurl: "/eposition"
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
